[huggingface]
model_name = "CohereForAI/c4ai-command-r-v01"
hugging_face_username = "thesven"

[gguf]
model_name_base = "c4ai-command-r-v01"
output_directory = "./models"
output_types = [
    "Q4_0",
    "Q4_1",
    "Q4_K",
    "Q4_K_S",
    "Q4_K_M",
    "Q2_K",
    "Q3_K",
    "Q3_K_S",
    "Q3_K_XS",
    "IQ2_K",
    "IQ3_S",
    "IQ3_XXS",
    "IQ4_NL",
    "IQ4_XS",
    "IQ5_K",
    "IQ2_S",
    "IQ2_XS",
    "IQ1_S"
]

[dataset]
imatrix = "calibration_data.txt"